openapi: 3.2.0
info:
  contact:
    email: support@tyk.io
    name: Tyk Technologies
    url: https://tyk.io/contact
  version: 1.0.0
  title: Tyk MDCB Data Planes and Diagnostics Env API
  description: 'This API provides operations for monitoring Data Planes connected to MDCB and accessing diagnostic data.  It includes endpoints for retrieving connected data plane details, performing health checks,  and accessing Go''s built-in pprof diagnostics for advanced performance profiling.

    '
servers:
- url: https://{tenant}
  variables:
    tenant:
      default: localhost:8181
      description: Your MDCB host
security:
- api_key: []
tags:
- name: Env
paths:
  /env:
    get:
      summary: Tyk Retrieve Environment Variables
      description: "Returns the current configuration status of the system.\n\n**Example curl command:**\n\n```bash\ncurl -X GET \\ \nhttp://localhost:8181/config\n-H 'X-Tyk-Authorization: your-secret-key'\n```\n"
      operationId: envGet
      parameters:
      - in: header
        name: X-Tyk-Authorization
        description: Secret value set in sink.conf
        required: true
        schema:
          type: string
        example: your-secret-key
      responses:
        '200':
          description: Successful retrieval of environment variables.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  example: TYK_MDCB_ANALYTICSSTORAGE_SSLINSECURESKIPVERIFY=false
        '401':
          description: Forbidden access due to invalid or missing administrative key.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      tags:
      - Env
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
components:
  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
          example: Attempted administrative access with invalid or missing key!
  securitySchemes:
    api_key:
      in: header
      name: X-Tyk-Authorization
      type: apiKey
