openapi: 3.2.0
info:
  contact:
    email: support@tyk.io
    name: Tyk Technologies
    url: https://tyk.io/contact
  description: 'The Tyk Gateway API is the primary means for integrating your application with the Tyk API Gateway system. This API is very small, and has no granular permissions system. It is intended to be used purely for internal automation and integration.


    **Warning: Under no circumstances should outside parties be granted access to this API.**


    The Tyk Gateway API is capable of:


    * Managing session objects (key generation).

    * Managing and listing policies.

    * Managing and listing API Definitions (only when not using the Tyk Dashboard).

    * Hot reloads / reloading a cluster configuration.

    * OAuth client creation (only when not using the Tyk Dashboard).


    In order to use the Gateway API, you''ll need to set the **secret** parameter in your tyk.conf file.


    The shared secret you set should then be sent along as a header with each Gateway API Request in order for it to be successful:


    **x-tyk-authorization: <your-secret>***

    <br/>


    <b>The Tyk Gateway API is subsumed by the Tyk Dashboard API in Pro installations.</b>


    '
  license:
    name: Mozilla Public License Version 2.0
    url: https://github.com/TykTechnologies/tyk/blob/master/LICENSE.md
  title: Tyk Gateway Health Checking API
  version: 5.7.1
servers:
- url: https://{tenant}
  variables:
    tenant:
      default: localhost:8080
      description: Your gateway host
security:
- api_key: []
tags:
- description: 'Check health status of the Tyk Gateway and loaded APIs.

    '
  name: Health Checking
paths:
  /hello:
    get:
      description: From v2.7.5 you can now rename the `/hello`  endpoint by using the `health_check_endpoint_name` option.
      operationId: hello
      responses:
        '200':
          content:
            application/json:
              example:
                description: Tyk GW
                details:
                  redis:
                    componentType: datastore
                    status: pass
                    time: '2020-05-19T03:42:55+01:00'
                status: pass
                version: v5.5.0-dev
              schema:
                $ref: '#/components/schemas/HealthCheckResponse'
          description: Success.
        '403':
          content:
            application/json:
              example:
                message: Attempted administrative access with invalid or missing key!
                status: error
              schema:
                $ref: '#/components/schemas/ApiStatusMessage'
          description: Forbidden
        '405':
          content:
            application/json:
              example:
                message: Method Not Allowed
                status: error
              schema:
                $ref: '#/components/schemas/ApiStatusMessage'
          description: Method Not Allowed
      summary: Check the Health of the Tyk Gateway.
      tags:
      - Health Checking
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
components:
  schemas:
    HealthCheckResponse:
      properties:
        description:
          type: string
          example: A sample description.
        details:
          additionalProperties:
            $ref: '#/components/schemas/HealthCheckItem'
          type: object
          example: example_value
        output:
          type: string
          example: example_value
        status:
          enum:
          - pass
          - fail
          - warn
          type: string
          example: pass
        version:
          type: string
          example: example_value
      type: object
    HealthCheckItem:
      properties:
        componentId:
          type: string
          example: '500123'
        componentType:
          type: string
          example: example_value
        output:
          type: string
          example: example_value
        status:
          enum:
          - pass
          - fail
          - warn
          type: string
          example: pass
        time:
          type: string
          example: example_value
      type: object
    ApiStatusMessage:
      properties:
        message:
          type: string
          example: example_value
        status:
          type: string
          example: example_value
      type: object
  securitySchemes:
    api_key:
      description: Api key
      in: header
      name: X-Tyk-Authorization
      type: apiKey
