openapi: 3.2.0
info:
  contact:
    email: support@tyk.io
    name: Tyk Technologies
    url: https://tyk.io/contact
  version: 1.0.0
  title: Tyk MDCB Data Planes and Diagnostics Liveness API
  description: 'This API provides operations for monitoring Data Planes connected to MDCB and accessing diagnostic data.  It includes endpoints for retrieving connected data plane details, performing health checks,  and accessing Go''s built-in pprof diagnostics for advanced performance profiling.

    '
servers:
- url: https://{tenant}
  variables:
    tenant:
      default: localhost:8181
      description: Your MDCB host
security:
- api_key: []
tags:
- name: Liveness
paths:
  /liveness:
    get:
      summary: Tyk Check Liveness Status
      description: Provides the liveness status of the service.
      operationId: livenessGet
      responses:
        '200':
          description: MDCB is alive.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LivenessStatus'
      tags:
      - Liveness
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
components:
  schemas:
    LivenessStatus:
      type: object
      properties:
        status:
          type: string
          example: pass
        status_code:
          type: integer
          example: 200
  securitySchemes:
    api_key:
      in: header
      name: X-Tyk-Authorization
      type: apiKey
