openapi: 3.2.0
info:
  contact:
    email: support@tyk.io
    name: Tyk Technologies
    url: https://tyk.io/contact
  version: 1.0.0
  title: Tyk MDCB Data Planes and Diagnostics Readiness API
  description: 'This API provides operations for monitoring Data Planes connected to MDCB and accessing diagnostic data.  It includes endpoints for retrieving connected data plane details, performing health checks,  and accessing Go''s built-in pprof diagnostics for advanced performance profiling.

    '
servers:
- url: https://{tenant}
  variables:
    tenant:
      default: localhost:8181
      description: Your MDCB host
security:
- api_key: []
tags:
- name: Readiness
paths:
  /readiness:
    get:
      summary: Tyk Check System Readiness Status
      description: 'Assesses the readiness of the system and its critical components. This endpoint determines if the system is prepared to handle requests by evaluating the status of essential services and dependencies.

        '
      operationId: readinessGet
      responses:
        '200':
          description: 'System is ready. All critical components are operational and  the system is capable of handling requests.

            '
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReadinessStatus'
        '503':
          description: 'System is not ready. One or more critical components are  non-operational, preventing the system from handling requests properly.

            '
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReadinessFailure'
      tags:
      - Readiness
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
components:
  schemas:
    ComponentReadiness:
      type: object
      properties:
        name:
          type: string
          example: postgres
        status:
          type: string
          example: pass
        observation_ts:
          type: string
          format: date-time
          example: '2024-07-29T13:58:56.699052-04:00'
    ComponentReadinessFailure:
      type: object
      properties:
        name:
          type: string
          example: postgres
        status:
          type: string
          example: fail
        observation_ts:
          type: string
          format: date-time
          example: '2024-07-29T13:58:56.699052-04:00'
    ReadinessFailure:
      type: object
      properties:
        status:
          type: string
          example: fail
        status_code:
          type: integer
          example: 503
        components:
          type: array
          items:
            $ref: '#/components/schemas/ComponentReadinessFailure'
          example: []
    ReadinessStatus:
      type: object
      properties:
        status:
          type: string
          example: pass
        status_code:
          type: integer
          example: 200
        components:
          type: array
          items:
            $ref: '#/components/schemas/ComponentReadiness'
          example: []
  securitySchemes:
    api_key:
      in: header
      name: X-Tyk-Authorization
      type: apiKey
