openapi: 3.2.0
info:
  contact:
    email: support@tyk.io
    name: Tyk Technologies
    url: https://tyk.io/contact
  description: The Tyk Gateway API is the primary means for integrating your application with the Tyk API Gateway system.
  license:
    name: Mozilla Public License Version 2.0
    url: https://github.com/TykTechnologies/tyk/blob/master/LICENSE.md
  title: Tyk Gateway Batch Requests API
  version: 5.7.1
servers:
- url: https://{tenant}
  variables:
    tenant:
      default: localhost:8080
      description: Your gateway host
security:
- api_key: []
tags:
- description: Tyk supports batch requests, so a client makes a single request to the API but gets a compound response object back.
  name: Batch Requests
paths:
  /{listen_path}/tyk/batch:
    post:
      description: Endpoint to run batch request.
      operationId: batch
      parameters:
      - description: API listen path
        example: get
        in: path
        name: listen_path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            example:
              requests:
              - body: ''
                headers:
                  authorization: 1dbc83b9c431649d7698faa9797e2900f
                  x-tyk-test: '1'
                  x-tyk-version: '1.2'
                method: GET
                relative_url: get
              - body: ''
                headers:
                  authorization: 1dbc83b9c431649d7698faa9797e2900f
                  x-tyk-test: '2'
                  x-tyk-version: '1.2'
                method: GET
                relative_url: get
              suppress_parallel_execution: false
            schema:
              $ref: '#/components/schemas/BatchRequestStructure'
      responses:
        '200':
          content:
            application/json:
              example:
              - body: '{"message": "success"}'
                code: 200
                headers:
                  Access-Control-Allow-Credentials:
                  - 'true'
                  Content-Type:
                  - application/json
                relative_url: get
              schema:
                items:
                  $ref: '#/components/schemas/BatchReplyUnit'
                type: array
          description: Success.
        '400':
          content:
            application/json:
              example:
                message: Batch request malformed
                status: error
              schema:
                $ref: '#/components/schemas/ApiStatusMessage'
          description: Bad Request
        '403':
          content:
            application/json:
              example:
                message: Attempted administrative access with invalid or missing key!
                status: error
              schema:
                $ref: '#/components/schemas/ApiStatusMessage'
          description: Forbidden
      summary: Tyk Run Batch Request
      tags:
      - Batch Requests
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
components:
  schemas:
    BatchReplyUnit:
      properties:
        body:
          type: string
          example: example_value
        code:
          type: integer
          example: 10
        headers:
          $ref: '#/components/schemas/HttpHeader'
        relative_url:
          type: string
          example: https://www.example.com
      type: object
    RequestDefinition:
      properties:
        body:
          type: string
          example: example_value
        headers:
          additionalProperties:
            type: string
          type:
          - object
          - 'null'
          example: example_value
        method:
          type: string
          example: example_value
        relative_url:
          type: string
          example: https://www.example.com
      type: object
    ApiStatusMessage:
      properties:
        message:
          type: string
          example: example_value
        status:
          type: string
          example: example_value
      type: object
    HttpHeader:
      additionalProperties:
        items:
          type: string
        type: array
      type: object
    BatchRequestStructure:
      properties:
        requests:
          items:
            $ref: '#/components/schemas/RequestDefinition'
          type:
          - array
          - 'null'
          example: []
        suppress_parallel_execution:
          type: boolean
          example: true
      type: object
  securitySchemes:
    api_key:
      description: Api key
      in: header
      name: X-Tyk-Authorization
      type: apiKey
