openapi: 3.2.0
info:
  contact:
    email: support@tyk.io
    name: Tyk Technologies
    url: https://tyk.io/contact
  description: '

    ## <a name="introduction"></a> Introduction


    The Tyk Dashboard API offers granular, programmatic access to a centralised database of resources that your Tyk nodes can pull from. This API has a dynamic user administrative structure which means the secret key that is used to communicate with your Tyk nodes can be kept secret and access to the wider management functions can be handled on a user-by-user and organisation-by-organisation basis.


    A common question around using a database-backed configuration is how to programmatically add API definitions to your Tyk nodes, the Dashboard API allows much more fine-grained, secure and multi-user access to your Tyk cluster, and should be used to manage a database-backed Tyk node.


    The Tyk Dashboard API works seamlessly with the Tyk Dashboard (and the two come bundled together).


    ## <a name="security-hierarchy"></a> Security Hierarchy


    The Dashboard API provides a more structured security layer to managing Tyk nodes.


    ### Organisations, APIs and Users


    With the Dashboard API and a database-backed Tyk setup, (and to an extent with file-based API setups - if diligence is used in naming and creating definitions), the following security model is applied to the management of Upstream APIs:


    * **Organisations**: All APIs are *owned* by an organisation, this is designated by the ''OrgID'' parameter in the API Definition.

    * **Users**: All users created in the Dashboard belong to an organisation (unless an exception is made for super-administrative access).

    * **APIs**: All APIs belong to an Organisation and only Users that belong to that organisation can see the analytics for those APIs and manage their configurations.

    * **API Keys**: API Keys are designated by organisation, this means an API key that has full access rights will not be allowed to access the APIs of another organisation on the same system, but can have full access to all APIs within the organisation.

    * **Access Rights**: Access rights are stored with the key, this enables a key to give access to multiple APIs, this is defined by the session object in the core Tyk API.


    In order to use the Dashboard API, you''ll need to get the ''Tyk Dashboard API Access Credentials'' secret from your user profile on the Dashboard UI.


    The secret you set should then be sent along as a header with each Dashboard API Request in order for it to be successful:



    authorization: <your-secret>

    '
  license:
    name: Mozilla Public License Version 2.0
    url: https://github.com/TykTechnologies/tyk/blob/master/LICENSE.md
  title: Tyk Dashboard System API
  version: 5.7.1
servers:
- url: https://{tenant}
  variables:
    tenant:
      default: localhost:8080
      description: Your dashboard host
security:
- bearerAuth: []
tags:
- description: System API.
  name: System
paths:
  /api/system/stats:
    get:
      description: Get system usage info with license entitlements for a specified date range. Return history for current and previous year if no date query parameters are provided.
      operationId: getSystemStats
      parameters:
      - $ref: '#/components/parameters/startDate'
      - $ref: '#/components/parameters/endDate'
      - description: Resolve daily.
        example: day
        in: query
        name: resolution
        required: false
        schema:
          enum:
          - day
          type: string
      - description: The entity for which stats should be retrieved.
        example: apis
        in: query
        name: entity
        required: false
        schema:
          default: apis
          enum:
          - apis
          - dataplanes
          - dataplanes.gateways
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SystemStatsResp'
          description: System statistics details.
        '400':
          content:
            application/json:
              example:
                Message: Request validation failed.
                Meta: null
                Status: Error
              schema:
                $ref: '#/components/schemas/ApiResponse'
          description: Bad request.
        '401':
          content:
            application/json:
              example:
                Message: Not authorised
                Meta: null
                Status: Error
              schema:
                $ref: '#/components/schemas/ApiResponse'
          description: Unauthorized
        '403':
          content:
            application/json:
              example:
                Message: 'access denied: You do not have permission to access  /api/system/stats'
                Meta: null
                Status: Error
              schema:
                $ref: '#/components/schemas/ApiResponse'
          description: Forbidden
        '404':
          content:
            application/json:
              example:
                Message: Stats not found.
                Meta: null
                Status: Error
              schema:
                $ref: '#/components/schemas/ApiResponse'
          description: Stats not found.
        '500':
          content:
            application/json:
              example:
                Message: Failed to system stats.
                Meta: null
                Status: Error
              schema:
                $ref: '#/components/schemas/ApiResponse'
          description: Internal server error.
      summary: Get system usage info.
      tags:
      - System
components:
  parameters:
    endDate:
      description: end date
      example: ' 2023-07-31'
      in: query
      name: end_day
      schema:
        format: date
        type: string
    startDate:
      description: start date
      example: '2023-07-01'
      in: query
      name: start_day
      schema:
        format: date
        type: string
  schemas:
    EntityStats:
      properties:
        apis:
          items:
            $ref: '#/components/schemas/IndividualStats'
          type:
          - array
          - 'null'
        dataplanes:
          items:
            $ref: '#/components/schemas/IndividualStats'
          type: array
        dataplanes_gateways:
          items:
            $ref: '#/components/schemas/IndividualStats'
          type: array
      type:
      - object
      - 'null'
    ApiResponse:
      properties:
        ID:
          type: string
        Message:
          type: string
        Meta: {}
        Status:
          type: string
      type: object
    SystemStatsResp:
      properties:
        message:
          type: string
        stats:
          $ref: '#/components/schemas/EntityStats'
        status:
          example: Success
          type: string
      type: object
    IndividualStats:
      properties:
        avg_active_usage:
          example: 13
          type: integer
        avg_usage:
          example: 15
          type: integer
        date:
          example: '2023-07-01'
          type: string
        license_entitlement:
          example: 25
          type: integer
        license_entitlement_active:
          example: 20
          type: integer
        max_active_usage:
          example: 18
          type: integer
        max_usage:
          example: 20
          type: integer
        min_active_usage:
          example: 8
          type: integer
        min_usage:
          example: 10
          type: integer
      type: object
  securitySchemes:
    bearerAuth:
      description: The Tyk Dashboard API Access Credentials
      scheme: bearer
      type: http
