openapi: 3.2.0
info:
  contact:
    email: support@tyk.io
    name: Tyk Technologies
    url: https://tyk.io/contact
  description: '## Introduction


    The Tyk Dashboard API offers granular, programmatic access to a centralised database of resources that your Tyk nodes can pull from.'
  license:
    name: Mozilla Public License Version 2.0
    url: https://github.com/TykTechnologies/tyk/blob/master/LICENSE.md
  title: Tyk Dashboard Open Policy Agent API
  version: 5.7.1
servers:
- url: https://{tenant}
  variables:
    tenant:
      default: localhost:8080
      description: Your dashboard host
security:
- bearerAuth: []
tags:
- description: The Tyk Dashboard permission system can be extended by writing custom rules using an Open Policy Agent (OPA).
  externalDocs:
    description: Tyk Open Policy Agent Full Documentation.
    url: https://tyk.io/docs/tyk-dashboard/open-policy-agent/
  name: Open Policy Agent
paths:
  /api/org/opa:
    get:
      description: List your organisation OPA rules.
      operationId: getOPARules
      responses:
        '200':
          content:
            application/json:
              example:
                open_policy:
                  rules: "package dashboard_users\ndefault request_intent = \"read\"\nrequest_intent = \"write\" { input.request.method == \"POST\" }\nrequest_intent = \"write\" { input.request.method == \"PUT\" }\nrequest_intent = \"delete\" { input.request.method == \"DELETE\" }\ndeny[\"You cannot create a keyless API.\"] {\n    request_intent == \"write\"\n    contains(input.request.path, \"api/apis\")\n    input.request.body.api_definition.use_keyless == true\n}"
              schema:
                $ref: '#/components/schemas/NewOPARules'
          description: OPA rules fetched.
        '401':
          content:
            application/json:
              example:
                Message: Not authorised
                Meta: null
                Status: Error
              schema:
                $ref: '#/components/schemas/ApiResponse'
          description: Unauthorized
        '403':
          content:
            application/json:
              example:
                Message: Your license does not support Open Policy.
                Meta: null
                Status: Error
              schema:
                $ref: '#/components/schemas/ApiResponse'
          description: Upgrade licence.
        '500':
          content:
            application/json:
              example:
                Message: Failed to identify organisation.
                Meta: null
                Status: Error
              schema:
                $ref: '#/components/schemas/ApiResponse'
          description: Internal server error.
      summary: List OPA rules
      tags:
      - Open Policy Agent
    put:
      description: Modify your OPA rules.
      operationId: updateOrgOPARules
      requestBody:
        content:
          application/json:
            example:
              open_policy:
                rules: "package dashboard_users\ndefault request_intent = \"read\"\nrequest_intent = \"write\" { input.request.method == \"POST\" }\nrequest_intent = \"write\" { input.request.method == \"PUT\" }\nrequest_intent = \"delete\" { input.request.method == \"DELETE\" }\ndeny[\"You cannot create a keyless API.\"] {\n    request_intent == \"write\"\n    contains(input.request.path, \"api/apis\")\n    input.request.body.api_definition.use_keyless == true\n}"
            schema:
              $ref: '#/components/schemas/NewOPARules'
        description: Create rule to prevent creation of keyless APIs.
      responses:
        '200':
          content:
            application/json:
              example:
                Message: OPA rules has been updated on org level.
                Meta: null
                Status: OK
              schema:
                $ref: '#/components/schemas/ApiResponse'
          description: OPA rules updated.
        '400':
          content:
            application/json:
              example:
                Message: Invalid OPA rules.
                Meta: null
                Status: Error
              schema:
                $ref: '#/components/schemas/ApiResponse'
          description: Invalid OPA rules.
        '401':
          content:
            application/json:
              example:
                Message: Not authorised
                Meta: null
                Status: Error
              schema:
                $ref: '#/components/schemas/ApiResponse'
          description: Unauthorized
        '403':
          content:
            application/json:
              example:
                Message: Your license does not support Open Policy.
                Meta: null
                Status: Error
              schema:
                $ref: '#/components/schemas/ApiResponse'
          description: Upgrade licence.
        '500':
          content:
            application/json:
              example:
                Message: Failed to unmarshal response body.
                Meta: null
                Status: Error
              schema:
                $ref: '#/components/schemas/ApiResponse'
          description: malformed request body.
      summary: Update OPA rules
      tags:
      - Open Policy Agent
components:
  schemas:
    NewOPARules:
      properties:
        open_policy:
          properties:
            rules:
              type: string
          type: object
      type: object
    ApiResponse:
      properties:
        ID:
          type: string
        Message:
          type: string
        Meta: {}
        Status:
          type: string
      type: object
  securitySchemes:
    bearerAuth:
      description: The Tyk Dashboard API Access Credentials
      scheme: bearer
      type: http
